# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b13afa8888006e9e7f9f93922166dc22834491777c02ed578db93424462a5c790927b2d914c1d664e9362cdd669f32e1c731dc97394cfe9ed4af94a4b77760

test:
  secret_key_base: 04a4545b75f48ec7eef78dc964ada9b62c41dfb241444fc7c6285b6ec7b953d823dd772ed483468a96bcd6ece2345668d6e3711d2c5f469c95e70858b0dece64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
